CREATE TABLE patients (
 patient_id BIGINT PRIMARY KEY, birth_date DATE NOT NULL, sex TEXT NOT NULL CHECK(sex IN ('F','M','X')),
 race_ethnicity TEXT, insurance_type TEXT NOT NULL, residential_region TEXT, created_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE hospitals (
 hospital_id BIGINT PRIMARY KEY, hospital_name TEXT NOT NULL UNIQUE, state TEXT NOT NULL,
 urban_rural TEXT NOT NULL CHECK(urban_rural IN ('urban','rural')), bed_count INTEGER NOT NULL CHECK(bed_count>0),
 teaching_status TEXT NOT NULL, ownership_type TEXT NOT NULL
);
CREATE TABLE providers (
 provider_id BIGINT PRIMARY KEY, hospital_id BIGINT NOT NULL REFERENCES hospitals(hospital_id),
 specialty TEXT NOT NULL, years_experience INTEGER NOT NULL CHECK(years_experience BETWEEN 0 AND 60)
);
CREATE TABLE encounters (
 encounter_id BIGINT PRIMARY KEY, patient_id BIGINT NOT NULL REFERENCES patients(patient_id),
 hospital_id BIGINT NOT NULL REFERENCES hospitals(hospital_id), provider_id BIGINT REFERENCES providers(provider_id),
 encounter_type TEXT NOT NULL CHECK(encounter_type IN ('inpatient','emergency','outpatient')),
 admission_date DATE NOT NULL, discharge_date DATE, discharge_disposition TEXT, total_cost DOUBLE PRECISION CHECK(total_cost>=0),
 mortality_flag INTEGER NOT NULL CHECK(mortality_flag IN (0,1)), complication_flag INTEGER NOT NULL CHECK(complication_flag IN (0,1))
);
CREATE TABLE diagnoses (
 diagnosis_id BIGINT PRIMARY KEY, diagnosis_code TEXT NOT NULL, diagnosis_name TEXT NOT NULL, diagnosis_category TEXT NOT NULL
);
CREATE TABLE encounter_diagnoses (
 encounter_id BIGINT NOT NULL REFERENCES encounters(encounter_id), diagnosis_id BIGINT NOT NULL REFERENCES diagnoses(diagnosis_id),
 diagnosis_rank INTEGER NOT NULL CHECK(diagnosis_rank>0), primary_diagnosis_flag INTEGER NOT NULL CHECK(primary_diagnosis_flag IN (0,1)),
 PRIMARY KEY(encounter_id, diagnosis_id)
);
CREATE TABLE procedures (
 procedure_id BIGINT PRIMARY KEY, procedure_code TEXT NOT NULL UNIQUE, procedure_name TEXT NOT NULL, procedure_category TEXT NOT NULL
);
CREATE TABLE encounter_procedures (
 encounter_id BIGINT NOT NULL REFERENCES encounters(encounter_id), procedure_id BIGINT NOT NULL REFERENCES procedures(procedure_id),
 procedure_date DATE NOT NULL, PRIMARY KEY(encounter_id, procedure_id)
);
CREATE TABLE lab_results (
 lab_result_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, encounter_id BIGINT NOT NULL REFERENCES encounters(encounter_id), lab_name TEXT NOT NULL,
 lab_value DOUBLE PRECISION, unit TEXT, reference_low DOUBLE PRECISION, reference_high DOUBLE PRECISION, collected_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE readmissions (
 readmission_id BIGINT PRIMARY KEY, index_encounter_id BIGINT NOT NULL UNIQUE REFERENCES encounters(encounter_id),
 readmission_encounter_id BIGINT REFERENCES encounters(encounter_id), days_to_readmission INTEGER,
 readmitted_within_30_days INTEGER NOT NULL CHECK(readmitted_within_30_days IN (0,1)), CHECK(days_to_readmission IS NULL OR days_to_readmission>=0)
);
CREATE TABLE quality_measures (
 quality_measure_id BIGINT PRIMARY KEY, hospital_id BIGINT NOT NULL REFERENCES hospitals(hospital_id), measure_name TEXT NOT NULL,
 measurement_period_start DATE NOT NULL, measurement_period_end DATE NOT NULL, numerator INTEGER NOT NULL,
 denominator INTEGER NOT NULL CHECK(denominator>0), measure_value DOUBLE PRECISION NOT NULL CHECK(measure_value BETWEEN 0 AND 1),
 UNIQUE(hospital_id, measure_name, measurement_period_start)
);
CREATE TABLE audit_runs (
 run_id TEXT PRIMARY KEY, user_question TEXT NOT NULL, normalized_question TEXT NOT NULL, model_name TEXT NOT NULL,
 schema_version TEXT NOT NULL, analysis_plan_json TEXT, generated_sql TEXT, validation_status TEXT NOT NULL,
 execution_status TEXT NOT NULL, result_row_count INTEGER NOT NULL DEFAULT 0, execution_time_ms DOUBLE PRECISION,
 statistical_tools_json TEXT, warnings_json TEXT, final_answer TEXT, created_at TIMESTAMPTZ NOT NULL, provenance_json TEXT
);
CREATE INDEX idx_encounters_dates ON encounters(admission_date, discharge_date);
CREATE INDEX idx_encounters_hospital ON encounters(hospital_id, admission_date);
CREATE INDEX idx_encounters_patient ON encounters(patient_id, admission_date);
CREATE INDEX idx_encounters_provider ON encounters(provider_id);
CREATE INDEX idx_ed_diagnosis ON encounter_diagnoses(diagnosis_id, encounter_id);
CREATE INDEX idx_readmissions_index ON readmissions(index_encounter_id, readmitted_within_30_days);
CREATE INDEX idx_quality_period ON quality_measures(measure_name, measurement_period_start);
CREATE INDEX idx_labs_encounter ON lab_results(encounter_id, lab_name);
CREATE VIEW encounter_facts AS
SELECT e.*, h.hospital_name, h.urban_rural, (e.discharge_date-e.admission_date) AS length_of_stay
FROM encounters e JOIN hospitals h ON h.hospital_id=e.hospital_id;
CREATE VIEW hospital_readmission_summary AS
SELECT h.hospital_id,h.hospital_name,COUNT(r.index_encounter_id) AS eligible_encounters,
       SUM(r.readmitted_within_30_days) AS readmissions,
       1.0*SUM(r.readmitted_within_30_days)/NULLIF(COUNT(r.index_encounter_id),0) AS readmission_rate
FROM hospitals h LEFT JOIN encounters e ON e.hospital_id=h.hospital_id
LEFT JOIN readmissions r ON r.index_encounter_id=e.encounter_id GROUP BY h.hospital_id,h.hospital_name;
