apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - postgres-bootstrap.yaml
  - storage.yaml
  - postgres.yaml
  - api.yaml
  - ui.yaml
  - airflow-scheduler.yaml
  - airflow-webserver.yaml
  - spark-job.yaml

